In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
dataset_df = pd.read_csv('../data/symptom_data/dataset.csv')
symptom_description_df = pd.read_csv('../data/symptom_data/symptom_Description.csv')
symptom_precaution_df = pd.read_csv('../data/symptom_data/symptom_precaution.csv')
symptom_severity_df = pd.read_csv('../data/symptom_data/Symptom-severity.csv')

In [4]:
dataset_df.head()

,Disease,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5,Symptom_6,Symptom_7,Symptom_8,Symptom_9,Symptom_10,Symptom_11,Symptom_12,Symptom_13,Symptom_14,Symptom_15,Symptom_16,Symptom_17
0,Fungal infection,itching,skin_rash,nodal_skin_eruptions,dischromic_patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Fungal infection,skin_rash,nodal_skin_eruptions,dischromic_patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Fungal infection,itching,nodal_skin_eruptions,dischromic_patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Fungal infection,itching,skin_rash,dischromic_patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Fungal infection,itching,skin_rash,nodal_skin_eruptions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
symptom_description_df.head()

          Disease                                        Description
0   Drug Reaction  An adverse drug reaction (ADR) is an injury ca...
1         Malaria  An infectious disease caused by protozoan para...
2         Allergy  An allergy is an immune system response to a f...
3  Hypothyroidism  Hypothyroidism, also called underactive thyroi...
4       Psoriasis  Psoriasis is a common skin disorder that forms...

In [6]:
symptom_precaution_df.head()

,Disease,Precaution_1,Precaution_2,Precaution_3,Precaution_4
0,Drug Reaction,stop irritation,consult nearest hospital,stop taking drug,follow up
1,Malaria,Consult nearest hospital,avoid oily food,avoid non veg food,keep mosquitoes out
2,Allergy,apply calamine,cover area with bandage,NaN,use ice to compress itching
3,Hypothyroidism,reduce stress,exercise,eat healthy,get proper sleep
4,Psoriasis,wash hands with warm soapy water,stop bleeding using pressure,consult doctor,salt baths

In [7]:
symptom_severity_df.head()

                Symptom  weight
0               itching       1
1             skin_rash       3
2  nodal_skin_eruptions       4
3   continuous_sneezing       4
4             shivering       5

In [8]:
# Check for duplicates on each dataset
print("Dataset Duplicates: ", dataset_df.duplicated().sum())
print("Symptom Description Duplicates: ", symptom_description_df.duplicated().sum())
print("Symptom Precause Duplicates: ", symptom_precaution_df.duplicated().sum())
print("Symptom Severity Duplicates: ", symptom_severity_df.duplicated().sum())

Dataset Duplicates:  4616
Symptom Description Duplicates:  0
Symptom Precause Duplicates:  0
Symptom Severity Duplicates:  0

In [9]:
# Check for missing values in each dataset
print("Symptom Description Missing Values: \n", symptom_description_df.isnull().sum())
print("-" * 50)
print("Symptom Precaution Missing Values: \n", symptom_precaution_df.isnull().sum())
print("-" * 50)
print("Symptom Severity Missing Values: \n", symptom_severity_df.isnull().sum())

Symptom Description Missing Values:
 Disease        0
Description    0
dtype: int64
--------------------------------------------------
Symptom Precaution Missing Values:
 Disease         0
Precaution_1    0
Precaution_2    0
Precaution_3    1
Precaution_4    1
dtype: int64
--------------------------------------------------
Symptom Severity Missing Values:
 Symptom    0
weight     0
dtype: int64

In [10]:
# Remove duplicates from dataset.csv 
dataset_df = dataset_df.drop_duplicates()

In [11]:
# Remove whitespace and underscoring from each column in each table 
dataset_cols = dataset_df.select_dtypes(object).columns
description_cols = symptom_description_df.select_dtypes(object).columns
precaution_cols = symptom_precaution_df.select_dtypes(object).columns
severity_cols = symptom_severity_df.select_dtypes(object).columns

dataset_df[dataset_cols] = dataset_df[dataset_cols].apply(
    lambda x: x.str.strip().str.lower().str.replace('_', ' ')
)
symptom_description_df[description_cols] = symptom_description_df[description_cols].apply(
    lambda x: x.str.strip().str.lower().str.replace('_', ' ')
)
symptom_precaution_df[precaution_cols] = symptom_precaution_df[precaution_cols].apply(
    lambda x: x.str.strip().str.lower().str.replace('_', ' ')
)
symptom_severity_df[severity_cols] = symptom_severity_df[severity_cols].apply(
    lambda x: x.str.strip().str.lower().str.replace('_', ' ')
)

In [12]:
# Remove missing values from dataset.csv
disease_set = set(dataset_df['Disease'])
dataset = dict()

for disease in disease_set:
    symptoms = dataset_df[dataset_df['Disease'] == disease].iloc[:, :-1].values
    dataset[disease] = []
    for symptom in symptoms:
        symptom = np.array(symptom[1:])

        cleaned = [
            s for s in symptom
            if (not pd.isna(s)) and (str(s).lower() != 'nan')
        ]

        dataset[disease].append(cleaned)

In [13]:
dataset

{'chicken pox': [['itching',
   'skin rash',
   'fatigue',
   'lethargy',
   'high fever',
   'headache',
   'loss of appetite',
   'mild fever',
   'swelled lymph nodes',
   'malaise',
   'red spots over body'],
  ['skin rash',
   'fatigue',
   'lethargy',
   'high fever',
   'headache',
   'loss of appetite',
   'mild fever',
   'swelled lymph nodes',
   'malaise',
   'red spots over body'],
  ['itching',
   'fatigue',
   'lethargy',
   'high fever',
   'headache',
   'loss of appetite',
   'mild fever',
   'swelled lymph nodes',
   'malaise',
   'red spots over body'],
  ['itching',
   'skin rash',
   'lethargy',
   'high fever',
   'headache',
   'loss of appetite',
   'mild fever',
   'swelled lymph nodes',
   'malaise',
   'red spots over body'],
  ['itching',
   'skin rash',
   'fatigue',
   'high fever',
   'headache',
   'loss of appetite',
   'mild fever',
   'swelled lymph nodes',
   'malaise',
   'red spots over body'],
  ['itching',
   'skin rash',
   'fatigue',
   'lethargy',
   'headache',
   'loss of appetite',
   'mild fever',
   'swelled lymph nodes',
   'malaise',
   'red spots over body'],
  ['itching',
   'skin rash',
   'fatigue',
   'lethargy',
   'high fever',
   'loss of appetite',
   'mild fever',
   'swelled lymph nodes',
   'malaise',
   'red spots over body'],
  ['itching',
   'skin rash',
   'fatigue',
   'lethargy',
   'high fever',
   'headache',
   'mild fever',
   'swelled lymph nodes',
   'malaise',
   'red spots over body'],
  ['itching',
   'skin rash',
   'fatigue',
   'lethargy',
   'high fever',
   'headache',
   'loss of appetite',
   'swelled lymph nodes',
   'malaise',
   'red spots over body'],
  ['itching',
   'skin rash',
   'fatigue',
   'lethargy',
   'high fever',
   'headache',
   'loss of appetite',
   'mild fever',
   'malaise',
   'red spots over body']],
 'cervical spondylosis': [['back pain',
   'weakness in limbs',
   'neck pain',
   'dizziness',
   'loss of balance'],
  ['weakness in limbs', 'neck pain', 'dizziness', 'loss of balance'],
  ['back pain', 'neck pain', 'dizziness', 'loss of balance'],
  ['back pain', 'weakness in limbs', 'dizziness', 'loss of balance'],
  ['back pain', 'weakness in limbs', 'neck pain', 'loss of balance'],
  ['back pain', 'weakness in limbs', 'neck pain', 'dizziness']],
 'hepatitis b': [['itching',
   'fatigue',
   'lethargy',
   'yellowish skin',
   'dark urine',
   'loss of appetite',
   'abdominal pain',
   'yellow urine',
   'yellowing of eyes',
   'malaise',
   'receiving blood transfusion',
   'receiving unsterile injections'],
  ['fatigue',
   'lethargy',
   'yellowish skin',
   'dark urine',
   'loss of appetite',
   'abdominal pain',
   'yellow urine',
   'yellowing of eyes',
   'malaise',
   'receiving blood transfusion',
   'receiving unsterile injections'],
  ['itching',
   'lethargy',
   'yellowish skin',
   'dark urine',
   'loss of appetite',
   'abdominal pain',
   'yellow urine',
   'yellowing of eyes',
   'malaise',
   'receiving blood transfusion',
   'receiving unsterile injections'],
  ['itching',
   'fatigue',
   'yellowish skin',
   'dark urine',
   'loss of appetite',
   'abdominal pain',
   'yellow urine',
   'yellowing of eyes',
   'malaise',
   'receiving blood transfusion',
   'receiving unsterile injections'],
  ['itching',
   'fatigue',
   'lethargy',
   'dark urine',
   'loss of appetite',
   'abdominal pain',
   'yellow urine',
   'yellowing of eyes',
   'malaise',
   'receiving blood transfusion',
   'receiving unsterile injections'],
  ['itching',
   'fatigue',
   'lethargy',
   'yellowish skin',
   'loss of appetite',
   'abdominal pain',
   'yellow urine',
   'yellowing of eyes',
   'malaise',
   'receiving blood transfusion',
   'receiving unsterile injections'],
  ['itching',
   'fatigue',
   'lethargy',
   'yellowish skin',
   'dark urine',
   'abdominal pain',
   'yellow urine',
   'yellowing of eyes',
   'malaise',
   'receiving blood transfusion',
   'receiving unsterile injections'],
  ['itching',
   'fatigue',
   'lethargy',
   'yellowish skin',
   'dark urine',
   'loss of appetite',
   'yellow urine',
   'yellowing of eyes',
   'malaise',
   'receiving blood transfusion',
   'receiving unsterile injections'],
  ['itching',
   'fatigue',
   'lethargy',
   'yellowish skin',
   'dark urine',
   'loss of appetite',
   'abdominal pain',
   'yellowing of eyes',
   'malaise',
   'receiving blood transfusion',
   'receiving unsterile injections']],
 'diabetes': [['fatigue',
   'weight loss',
   'restlessness',
   'lethargy',
   'irregular sugar level',
   'blurred and distorted vision',
   'obesity',
   'excessive hunger',
   'increased appetite',
   'polyuria'],
  ['weight loss',
   'restlessness',
   'lethargy',
   'irregular sugar level',
   'blurred and distorted vision',
   'obesity',
   'excessive hunger',
   'increased appetite',
   'polyuria'],
  ['fatigue',
   'restlessness',
   'lethargy',
   'irregular sugar level',
   'blurred and distorted vision',
   'obesity',
   'excessive hunger',
   'increased appetite',
   'polyuria'],
  ['fatigue',
   'weight loss',
   'lethargy',
   'irregular sugar level',
   'blurred and distorted vision',
   'obesity',
   'excessive hunger',
   'increased appetite',
   'polyuria'],
  ['fatigue',
   'weight loss',
   'restlessness',
   'irregular sugar level',
   'blurred and distorted vision',
   'obesity',
   'excessive hunger',
   'increased appetite',
   'polyuria'],
  ['fatigue',
   'weight loss',
   'restlessness',
   'lethargy',
   'blurred and distorted vision',
   'obesity',
   'excessive hunger',
   'increased appetite',
   'polyuria'],
  ['fatigue',
   'weight loss',
   'restlessness',
   'lethargy',
   'irregular sugar level',
   'obesity',
   'excessive hunger',
   'increased appetite',
   'polyuria'],
  ['fatigue',
   'weight loss',
   'restlessness',
   'lethargy',
   'irregular sugar level',
   'blurred and distorted vision',
   'excessive hunger',
   'increased appetite',
   'polyuria'],
  ['fatigue',
   'weight loss',
   'restlessness',
   'lethargy',
   'irregular sugar level',
   'blurred and distorted vision',
   'obesity',
   'increased appetite',
   'polyuria']],
 'hepatitis d': [['joint pain',
   'vomiting',
   'fatigue',
   'yellowish skin',
   'dark urine',
   'nausea',
   'loss of appetite',
   'abdominal pain',
   'yellowing of eyes'],
  ['vomiting',
   'fatigue',
   'yellowish skin',
   'dark urine',
   'nausea',
   'loss of appetite',
   'abdominal pain',
   'yellowing of eyes'],
  ['joint pain',
   'fatigue',
   'yellowish skin',
   'dark urine',
   'nausea',
   'loss of appetite',
   'abdominal pain',
   'yellowing of eyes'],
  ['joint pain',
   'vomiting',
   'yellowish skin',
   'dark urine',
   'nausea',
   'loss of appetite',
   'abdominal pain',
   'yellowing of eyes'],
  ['joint pain',
   'vomiting',
   'fatigue',
   'dark urine',
   'nausea',
   'loss of appetite',
   'abdominal pain',
   'yellowing of eyes'],
  ['joint pain',
   'vomiting',
   'fatigue',
   'yellowish skin',
   'nausea',
   'loss of appetite',
   'abdominal pain',
   'yellowing of eyes'],
  ['joint pain',
   'vomiting',
   'fatigue',
   'yellowish skin',
   'dark urine',
   'loss of appetite',
   'abdominal pain',
   'yellowing of eyes'],
  ['joint pain',
   'vomiting',
   'fatigue',
   'yellowish skin',
   'dark urine',
   'nausea',
   'abdominal pain',
   'yellowing of eyes'],
  ['joint pain',
   'vomiting',
   'fatigue',
   'yellowish skin',
   'dark urine',
   'nausea',
   'loss of appetite',
   'yellowing of eyes'],
  ['joint pain',
   'vomiting',
   'fatigue',
   'yellowish skin',
   'dark urine',
   'nausea',
   'loss of appetite',
   'abdominal pain']],
 'pneumonia': [['chills',
   'fatigue',
   'cough',
   'high fever',
   'breathlessness',
   'sweating',
   'malaise',
   'chest pain',
   'fast heart rate',
   'rusty sputum'],
  ['chills',
   'fatigue',
   'cough',
   'high fever',
   'breathlessness',
   'sweating',
   'malaise',
   'phlegm',
   'chest pain',
   'fast heart rate',
   'rusty sputum'],
  ['fatigue',
   'cough',
   'high fever',
   'breathlessness',
   'sweating',
   'malaise',
   'phlegm',
   'chest pain',
   'fast heart rate',
   'rusty sputum'],
  ['chills',
   'cough',
   'high fever',
   'breathlessness',
   'sweating',
   'malaise',
   'phlegm',
   'chest pain',
   'fast heart rate',
   'rusty sputum'],
  ['chills',
   'fatigue',
   'high fever',
   'breathlessness',
   'sweating',
   'malaise',
   'phlegm',
   'chest pain',
   'fast heart rate',
   'rusty sputum'],
  ['chills',
   'fatigue',
   'cough',
   'breathlessness',
   'sweating',
   'malaise',
   'phlegm',
   'chest pain',
   'fast heart rate',
   'rusty sputum'],
  ['chills',
   'fatigue',
   'cough',
   'high fever',
   'sweating',
   'malaise',
   'phlegm',
   'chest pain',
   'fast heart rate',
   'rusty sputum'],
  ['chills',
   'fatigue',
   'cough',
   'high fever',
   'breathlessness',
   'malaise',
   'phlegm',
   'chest pain',
   'fast heart rate',
   'rusty sputum'],
  ['chills',
   'fatigue',
   'cough',
   'high fever',
   'breathlessness',
   'sweating',
   'phlegm',
   'chest pain',
   'fast heart rate',
   'rusty sputum']],
 'hyperthyroidism': [['fatigue',
   'mood swings',
   'weight loss',
   'restlessness',
   'sweating',
   'diarrhoea',
   'fast heart rate',
   'excessive hunger',
   'muscle weakness',
   'irritability',
   'abnormal menstruation'],
  ['mood swings',
   'weight loss',
   'restlessness',
   'sweating',
   'diarrhoea',
   'fast heart rate',
   'excessive hunger',
   'muscle weakness',
   'irritability',
   'abnormal menstruation'],
  ['fatigue',
   'weight loss',
   'restlessness',
   'sweating',
   'diarrhoea',
   'fast heart rate',
   'excessive hunger',
   'muscle weakness',
   'irritability',
   'abnormal menstruation'],
  ['fatigue',
   'mood swings',
   'restlessness',
   'sweating',
   'diarrhoea',
   'fast heart rate',
   'excessive hunger',
   'muscle weakness',
   'irritability',
   'abnormal menstruation'],
  ['fatigue',
   'mood swings',
   'weight loss',
   'sweating',
   'diarrhoea',
   'fast heart rate',
   'excessive hunger',
   'muscle weakness',
   'irritability',
   'abnormal menstruation'],
  ['fatigue',
   'mood swings',
   'weight loss',
   'restlessness',
   'diarrhoea',
   'fast heart rate',
   'excessive hunger',
   'muscle weakness',
   'irritability',
   'abnormal menstruation'],
  ['fatigue',
   'mood swings',
   'weight loss',
   'restlessness',
   'sweating',
   'fast heart rate',
   'excessive hunger',
   'muscle weakness',
   'irritability',
   'abnormal menstruation'],
  ['fatigue',
   'mood swings',
   'weight loss',
   'restlessness',
   'sweating',
   'diarrhoea',
   'excessive hunger',
   'muscle weakness',
   'irritability',
   'abnormal menstruation'],
  ['fatigue',
   'mood swings',
   'weight loss',
   'restlessness',
   'sweating',
   'diarrhoea',
   'fast heart rate',
   'muscle weakness',
   'irritability',
   'abnormal menstruation']],
 'hypoglycemia': [['vomiting',
   'fatigue',
   'anxiety',
   'sweating',
   'headache',
   'nausea',
   'blurred and distorted vision',
   'excessive hunger',
   'slurred speech',
   'irritability',
   'palpitations'],
  ['vomiting',
   'fatigue',
   'anxiety',
   'sweating',
   'headache',
   'nausea',
   'blurred and distorted vision',
   'excessive hunger',
   'drying and tingling lips',
   'slurred speech',
   'irritability',
   'palpitations'],
  ['fatigue',
   'anxiety',
   'sweating',
   'headache',
   'nausea',
   'blurred and distorted vision',
   'excessive hunger',
   'drying and tingling lips',
   'slurred speech',
   'irritability',
   'palpitations'],
  ['vomiting',
   'anxiety',
   'sweating',
   'headache',
   'nausea',
   'blurred and distorted vision',
   'excessive hunger',
   'drying and tingling lips',
   'slurred speech',
   'irritability',
   'palpitations'],
  ['vomiting',
   'fatigue',
   'sweating',
   'headache',
   'nausea',
   'blurred and distorted vision',
   'excessive hunger',
   'drying and tingling lips',
   'slurred speech',
   'irritability',
   'palpitations'],
  ['vomiting',
   'fatigue',
   'anxiety',
   'headache',
   'nausea',
   'blurred and distorted vision',
   'excessive hunger',
   'drying and tingling lips',
   'slurred speech',
   'irritability',
   'palpitations'],
  ['vomiting',
   'fatigue',
   'anxiety',
   'sweating',
   'nausea',
   'blurred and distorted vision',
   'excessive hunger',
   'drying and tingling lips',
   'slurred speech',
   'irritability',
   'palpitations'],
  ['vomiting',
   'fatigue',
   'anxiety',
   'sweating',
   'headache',
   'blurred and distorted vision',
   'excessive hunger',
   'drying and tingling lips',
   'slurred speech',
   'irritability',
   'palpitations'],
  ['vomiting',
   'fatigue',
   'anxiety',
   'sweating',
   'headache',
   'nausea',
   'excessive hunger',
   'drying and tingling lips',
   'slurred speech',
   'irritability',
   'palpitations']],
 'impetigo': [['skin rash',
   'high fever',
   'blister',
   'red sore around nose',
   'yellow crust ooze'],
  ['high fever', 'blister', 'red sore around nose', 'yellow crust ooze'],
  ['skin rash', 'blister', 'red sore around nose', 'yellow crust ooze'],
  ['skin rash', 'high fever', 'red sore around nose', 'yellow crust ooze'],
  ['skin rash', 'high fever', 'blister', 'yellow crust ooze'],
  ['skin rash', 'high fever', 'blister', 'red sore around nose']],
 'arthritis': [['muscle weakness',
   'stiff neck',
   'swelling joints',
   'movement stiffness',
   'painful walking'],
  ['stiff neck', 'swelling joints', 'movement stiffness', 'painful walking'],
  ['muscle weakness',
   'swelling joints',
   'movement stiffness',
   'painful walking'],
  ['muscle weakness', 'stiff neck', 'movement stiffness', 'painful walking'],
  ['muscle weakness', 'stiff neck', 'swelling joints', 'painful walking'],
  ['muscle weakness', 'stiff neck', 'swelling joints', 'movement stiffness']],
 '(vertigo) paroymsal  positional vertigo': [['vomiting',
   'headache',
   'nausea',
   'spinning movements',
   'loss of balance',
   'unsteadiness'],
  ['headache',
   'nausea',
   'spinning movements',
   'loss of balance',
   'unsteadiness'],
  ['vomiting',
   'nausea',
   'spinning movements',
   'loss of balance',
   'unsteadiness'],
  ['vomiting',
   'headache',
   'spinning movements',
   'loss of balance',
   'unsteadiness'],
  ['vomiting', 'headache', 'nausea', 'loss of balance', 'unsteadiness'],
  ['vomiting', 'headache', 'nausea', 'spinning movements', 'unsteadiness'],
  ['vomiting', 'headache', 'nausea', 'spinning movements', 'loss of balance']],
 'hypothyroidism': [['fatigue',
   'weight gain',
   'cold hands and feets',
   'mood swings',
   'lethargy',
   'dizziness',
   'puffy face and eyes',
   'enlarged thyroid',
   'brittle nails',
   'swollen extremeties',
   'depression',
   'irritability',
   'abnormal menstruation'],
  ['weight gain',
   'cold hands and feets',
   'mood swings',
   'lethargy',
   'dizziness',
   'puffy face and eyes',
   'enlarged thyroid',
   'brittle nails',
   'swollen extremeties',
   'depression',
   'irritability',
   'abnormal menstruation'],
  ['fatigue',
   'cold hands and feets',
   'mood swings',
   'lethargy',
   'dizziness',
   'puffy face and eyes',
   'enlarged thyroid',
   'brittle nails',
   'swollen extremeties',
   'depression',
   'irritability',
   'abnormal menstruation'],
  ['fatigue',
   'weight gain',
   'mood swings',
   'lethargy',
   'dizziness',
   'puffy face and eyes',
   'enlarged thyroid',
   'brittle nails',
   'swollen extremeties',
   'depression',
   'irritability',
   'abnormal menstruation'],
  ['fatigue',
   'weight gain',
   'cold hands and feets',
   'lethargy',
   'dizziness',
   'puffy face and eyes',
   'enlarged thyroid',
   'brittle nails',
   'swollen extremeties',
   'depression',
   'irritability',
   'abnormal menstruation'],
  ['fatigue',
   'weight gain',
   'cold hands and feets',
   'mood swings',
   'dizziness',
   'puffy face and eyes',
   'enlarged thyroid',
   'brittle nails',
   'swollen extremeties',
   'depression',
   'irritability',
   'abnormal menstruation'],
  ['fatigue',
   'weight gain',
   'cold hands and feets',
   'mood swings',
   'lethargy',
   'puffy face and eyes',
   'enlarged thyroid',
   'brittle nails',
   'swollen extremeties',
   'depression',
   'irritability',
   'abnormal menstruation'],
  ['fatigue',
   'weight gain',
   'cold hands and feets',
   'mood swings',
   'lethargy',
   'dizziness',
   'enlarged thyroid',
   'brittle nails',
   'swollen extremeties',
   'depression',
   'irritability',
   'abnormal menstruation']],
 'typhoid': [['chills',
   'vomiting',
   'fatigue',
   'high fever',
   'nausea',
   'constipation',
   'abdominal pain',
   'diarrhoea',
   'toxic look (typhos)',
   'belly pain'],
  ['chills',
   'vomiting',
   'fatigue',
   'high fever',
   'headache',
   'constipation',
   'abdominal pain',
   'diarrhoea',
   'toxic look (typhos)',
   'belly pain'],
  ['chills',
   'vomiting',
   'fatigue',
   'high fever',
   'headache',
   'nausea',
   'abdominal pain',
   'diarrhoea',
   'toxic look (typhos)',
   'belly pain'],
  ['chills',
   'vomiting',
   'fatigue',
   'high fever',
   'headache',
   'nausea',
   'constipation',
   'diarrhoea',
   'toxic look (typhos)',
   'belly pain'],
  ['chills',
   'vomiting',
   'fatigue',
   'high fever',
   'headache',
   'nausea',
   'constipation',
   'abdominal pain',
   'toxic look (typhos)',
   'belly pain'],
  ['chills',
   'vomiting',
   'fatigue',
   'high fever',
   'headache',
   'nausea',
   'constipation',
   'abdominal pain',
   'diarrhoea',
   'belly pain'],
  ['chills',
   'vomiting',
   'fatigue',
   'high fever',
   'headache',
   'nausea',
   'constipation',
   'abdominal pain',
   'diarrhoea',
   'toxic look (typhos)'],
  ['chills',
   'vomiting',
   'fatigue',
   'high fever',
   'headache',
   'nausea',
   'constipation',
   'abdominal pain',
   'diarrhoea',
   'toxic look (typhos)',
   'belly pain'],
  ['chills',
   'fatigue',
   'high fever',
   'headache',
   'nausea',
   'constipation',
   'abdominal pain',
   'diarrhoea',
   'toxic look (typhos)',
   'belly pain']],
 'heart attack': [['vomiting', 'breathlessness', 'sweating', 'chest pain'],
  ['breathlessness', 'sweating', 'chest pain'],
  ['vomiting', 'sweating', 'chest pain'],
  ['vomiting', 'breathlessness', 'chest pain'],
  ['vomiting', 'breathlessness', 'sweating']],
 'hepatitis e': [['joint pain',
   'vomiting',
   'fatigue',
   'high fever',
   'yellowish skin',
   'dark urine',
   'nausea',
   'loss of appetite',
   'abdominal pain',
   'yellowing of eyes',
   'coma',
   'stomach bleeding'],
  ['joint pain',
   'vomiting',
   'fatigue',
   'high fever',
   'yellowish skin',
   'dark urine',
   'nausea',
   'loss of appetite',
   'abdominal pain',
   'yellowing of eyes',
   'acute liver failure',
   'coma',
   'stomach bleeding'],
  ['vomiting',
   'fatigue',
   'high fever',
   'yellowish skin',
   'dark urine',
   'nausea',
   'loss of appetite',
   'abdominal pain',
   'yellowing of eyes',
   'acute liver failure',
   'coma',
   'stomach bleeding'],
  ['joint pain',
   'fatigue',
   'high fever',
   'yellowish skin',
   'dark urine',
   'nausea',
   'loss of appetite',
   'abdominal pain',
   'yellowing of eyes',
   'acute liver failure',
   'coma',
   'stomach bleeding'],
  ['joint pain',
   'vomiting',
   'high fever',
   'yellowish skin',
   'dark urine',
   'nausea',
   'loss of appetite',
   'abdominal pain',
   'yellowing of eyes',
   'acute liver failure',
   'coma',
   'stomach bleeding'],
  ['joint pain',
   'vomiting',
   'fatigue',
   'yellowish skin',
   'dark urine',
   'nausea',
   'loss of appetite',
   'abdominal pain',
   'yellowing of eyes',
   'acute liver failure',
   'coma',
   'stomach bleeding'],
  ['joint pain',
   'vomiting',
   'fatigue',
   'high fever',
   'dark urine',
   'nausea',
   'loss of appetite',
   'abdominal pain',

In [14]:
# Replace NaN/missing column values with "no specific precautions" since there is only 2
text = "no specific precautions"
symptom_precaution_df.fillna({"Precaution_3": text, "Precaution_4": text}, inplace=True)

In [15]:
severity_lookup = symptom_severity_df.assign(
    Symptom=symptom_severity_df['Symptom']
).set_index('Symptom')['weight'].to_dict()

# Get the weight of a symptom
def get_symptom_weight(symptom):
    if pd.isna(symptom):
        return None 

    if symptom is None:
        return None 
    
    weight = severity_lookup.get(symptom)

    if weight is None:
        raise KeyError(f"Symptom '{symptom}' was not found in Symptom-severity.csv")

    return int(weight)

In [16]:
# Merge each of the four tables into a single dataset
symptom_dataset = list()

for disease in disease_set:

    description = symptom_description_df[symptom_description_df['Disease'] == disease]['Description'].iloc[0]
    precautions = list(symptom_precaution_df[symptom_precaution_df['Disease'] == disease].iloc[0, 1:])
    
    for combination in dataset[disease]:
        
        entry = dict()

        entry['disease'] = disease
        entry['description'] = description 
        entry['symptoms'] = combination
        entry['precaution'] = precautions 
        entry['severity'] = [get_symptom_weight(s) for s in combination]

    
        symptom_dataset.append(entry)

In [19]:
import json 
with open("../JSON_data/symptom_dataset.json", "w") as file:
    json.dump(symptom_dataset, file, indent=2)